// 词条中文映射，搬自 DADEquipment frontend/public/data/stats/game-constants.json 的 attributes 段（反转为 key → 中文）
export const ATTR_ZH = {
  strength: '力量',
  vigor: '活力',
  agility: '敏捷',
  dexterity: '灵巧',
  will: '意志',
  knowledge: '知识',
  resourcefulness: '智谋',
  all_attributes: '全属性',
  max_health: '最大生命值',
  max_health_bonus: '最大生命值加成',
  weapon_damage: '武器伤害',
  physical_healing: '物理治疗',
  magical_healing: '魔法治疗',
  additional_weapon_damage: '额外武器伤害',
  magic_weapon_damage: '魔法武器伤害',
  additional_physical_damage: '额外物理伤害',
  additional_magical_damage: '额外魔法伤害',
  magical_damage: '魔法伤害',
  true_physical_damage: '真实物理伤害',
  true_magical_damage: '真实魔法伤害',
  move_speed: '移动速度',
  additional_memory_capacity: '额外记忆容量',
  memory_capacity_bonus: '记忆容量加成',
  memory_capacity: '记忆容量',
  spell_memory_load: '法术记忆负载',
  song_memory_load: '乐谱记忆负载',
  consumable_effect: '消耗品效果',
  spell_cap: '法术上限',
  luck: '幸运',
  health_recovery_bonus: '血量恢复加成',
  spell_recovery_bonus: '法术恢复加成',
  action_speed: '动作速度',
  spell_casting_speed: '施法速度',
  regular_interaction_speed: '常规交互速度',
  magical_interaction_speed: '魔法交互速度',
  interaction_speed: '交互速度',
  additional_move_speed: '额外移动速度',
  move_speed_bonus: '移动速度加成',
  buff_duration_bonus: '增益持续时间加成',
  debuff_duration_bonus: '减益持续时间加成',
  cooldown_reduction_bonus: '缩短冷却时间加成',
  armor_penetration: '护甲穿透',
  magic_penetration: '魔法穿透',
  headshot_damage_bonus: '爆头伤害加成',
  headshot_damage_reduction: '爆头伤害减免',
  projectile_damage_reduction: '飞行物伤害减免',
  physical_damage_reduction: '物理伤害减免',
  magical_damage_reduction: '魔法伤害减免',
  armor_rating: '护甲值',
  base_armor_rating: '基础护甲值',
  additional_armor_rating: '额外护甲值',
  magic_resistance: '魔法抗性',
  physical_damage: '物理伤害',
  physical_power: '物理强度',
  physical_power_bonus: '物理强度加成',
  physical_damage_bonus: '物理伤害加成',
  magical_power: '魔法强度',
  magical_power_bonus: '魔法强度加成',
  magical_damage_bonus: '魔法伤害加成',
  undead_damage_bonus: '亡灵伤害加成',
  undead_damage_reduction: '亡灵伤害减免',
  demon_damage_bonus: '恶魔伤害加成',
  demon_damage_reduction: '恶魔伤害减免',
  manual_dexterity: '手艺效率',
  item_equip_speed: '道具装备速度',
  persuasiveness: '口才',
  buff_duration: '增益持续时间',
  debuff_duration: '减益持续时间',
};

export function attrField (display) {
  return String (display || '').toLowerCase ().replace (/ /g, '_');
}

export function attrZhByDisplay (display) {
  return ATTR_ZH[attrField (display)] || display;
}
